typography_spectrum: 0.2449321064632386
color:
  brandStrength: 0.04030027752742171
  lightness: 0.648656613426283
  saturation: 0.19082886446267366
  rhythmicContrast: 0.7787368991412222
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
layout_spectrum: 0.559477727394551
name: Nudge
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/fa5b33cd-878d-4066-9a47-0235245f665a.jpg
title: Changing behaviour at  scale
